WARNING  urllib3.connectionpool:connectionpool.py:810 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000027A007B5930>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/f26f289e522a45a37a10a441857bc342/window
WARNING  urllib3.connectionpool:connectionpool.py:810 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000027A0123F310>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/f26f289e522a45a37a10a441857bc342/window
WARNING  urllib3.connectionpool:connectionpool.py:810 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000027A0123F160>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/f26f289e522a45a37a10a441857bc342/window
